### ISSUE TITLE
生成图片的头像是黑色的

### ISSUE THREAD

**Issue by YatsukiRenka** [YKilin/osusig#1]
![image](https://user-images.githubusercontent.com/38554950/69113653-951d2280-0abe-11ea-8039-d19689ba53fd.png)
![image](https://user-images.githubusercontent.com/38554950/69113636-86367000-0abe-11ea-9a6f-efeb0ae8eadf.png)

大佬您好，我在自己的站点上尝试搭建osusig的时候出现了这种头像上像是被蒙了一层黑色图层的情况，您能帮忙查看一下是什么问题吗？
[https://osusig.kotoka.tech](url)

**Comment by Tsuk1ko** [comment]
抱歉，之前不知道为什么把仓库的 watch 取消了结果没收到这条 issue 的提醒

试下拉取最新代码，如果还有问题可以参考我正常运行的配置

- PHP 7.3.15 (imagick module 3.4.4)
- ImageMagick 6.7.8-9

**Comment by YatsukiRenka** [comment]
整好了，谢谢大佬指点
